            - nom : Télécharger un artefact de construction
  utilisations : actions/upload-artifact@v4.4.3
  avec:
    # Nom de l'artefact
    nom : # facultatif, la valeur par défaut est un artefact
    # Un fichier, un répertoire ou un modèle générique qui décrit ce qu'il faut télécharger
    chemin:
    # Le comportement souhaité si aucun fichier n'est trouvé en utilisant le chemin fourni.
Options disponibles :
  warn : afficher un avertissement mais ne pas faire échouer l'action
  erreur : échouer l'action avec un message d'erreur
  ignorer : ne pas générer d'avertissements ni d'erreurs, l'action n'échoue pas

    if-no-files-found: # facultatif, la valeur par défaut est warn
    # Durée après laquelle l'artefact expirera en jours. 0 signifie utiliser la rétention par défaut.
Minimum 1 jour. Maximum 90 jours sauf modification depuis la page des paramètres du référentiel.

    jours de rétention : # facultatif
    # Le niveau de compression de Zlib à appliquer à l'archive d'artefacts. La valeur peut aller de 0 à 9 : - 0 : Aucune compression - 1 : Meilleure vitesse - 6 : Compression par défaut (identique à GNU Gzip) - 9 : Meilleure compression Des niveaux plus élevés donneront lieu à une meilleure compression, mais prendront plus de temps à effectuer. Pour les fichiers volumineux qui ne sont pas facilement compressés, une valeur de 0 est recommandée pour des téléchargements nettement plus rapides.

    niveau de compression : # facultatif, la valeur par défaut est 6
    # Si la valeur est true, un artefact portant un nom correspondant sera supprimé avant qu'un nouveau ne soit téléchargé. Si la valeur est false, l'action échouera si un artefact portant le nom donné existe déjà. N'échoue pas si l'artefact n'existe pas.

    écraser : # facultatif, la valeur par défaut est false
    # Si vrai, les fichiers cachés seront inclus dans l'artefact. Si faux, les fichiers cachés seront exclus de l'artefact.

    include-hidden-files: # facultatif, la valeur par défaut est false
          
